#!/bin/bash
# Real device deployment requires Xcode codesigning.
# This script guides you through the process.
set -euo pipefail

echo "╔══════════════════════════════════════════════╗"
echo "║  MacRelay iOS — Real Device Deployment      ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "SwiftPM cannot codesign for real devices."
echo "Use Xcode for device deployment:"
echo ""
echo "  1. Open the project in Xcode:"
echo "     open Package.swift"
echo ""
echo "  2. Select the 'MacRelayiOS' scheme (top-left)."
echo ""
echo "  3. Choose your connected iPhone as the"
echo "     destination (instead of a simulator)."
echo ""
echo "  4. In 'Signing & Capabilities':"
echo "     - Check 'Automatically manage signing'"
echo "     - Team: select your Personal Team"
echo "     - Bundle Identifier: com.xiangyingchang.macrelay"
echo ""
echo "  5. Press ⌘R to build and run on your device."
echo ""
echo "If the device is not listed:"
echo "  - Connect via USB cable"
echo "  - Trust the computer on the iPhone"
echo "  - In Xcode → Window → Devices, verify it appears"
echo ""
echo "For simulator (no signing needed):"
echo "  ./scripts/build-ios.sh"
