#!/bin/bash
# Real device deployment — must use the Xcode App project.
set -euo pipefail

echo "╔══════════════════════════════════════════════╗"
echo "║  MacRelay iOS — Real Device Deployment      ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Open the Xcode App project:"
echo "  open Apps/MacRelayiOSApp/MacRelayiOSApp.xcodeproj"
echo ""
echo "Then:"
echo "  1. Select 'MacRelayiOSApp' scheme (top-left)"
echo "  2. Choose your connected iPhone as destination"
echo "  3. Signing & Capabilities → Team: Personal Team"
echo "     (Xcode auto-creates provisioning profile)"
echo "  4. Press ⌘R to build, sign, and run on device"
echo ""
echo "Troubleshooting:"
echo "  - Device not listed: connect via USB, trust computer"
echo "  - Signing fails: verify Apple ID in Xcode → Accounts"
echo "  - Bundle ID conflict: change in target → General"
echo ""
echo "For simulator (no signing needed):"
echo "  ./scripts/build-ios.sh"
